language: r
warnings_are_errors: true
sudo: required

matrix:
  include:
    - env: RVER=STD GGPLOT=DEV
    - env: RVER=STD GGPLOT=STD
    - env: RVER=DEV GGPLOT=STD

r_binary_packages:
  - dplyr
  - tidyr
  - proto
  - ggplot2
  - testthat
  - changepoint
  - dlm
  # - fGarch
  - forecast
  - KFAS
  - knitr
  - MASS
  - MSwM
  - strucchange
  - survival
  - timeSeries
  - vars
  - xts

r_github_packages:
  - jimhester/covr

before_install:
  - if [[ "$RVER" == "DEV" ]]; then
      sh install_rdevel.sh;
    fi
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile
  - if [[ "$GGPLOT" == "DEV" ]]; then
      Rscript -e 'install.packages("devtools")';
      Rscript -e 'library(devtools);install_github("hadley/ggplot2")';
    fi
  # install latest
  - Rscript -e 'install.packages("roxygen2")';

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - R --version
  - Rscript -e 'library("ggplot2"); packageVersion("ggplot2")'
